import Header from "@/components/Header"
import { EachProjectData } from "@/datas";
import Head from "next/head"
import { useRouter } from "next/router"

const ProjectDetail = () => {
    const router = useRouter();
    const props = router.query;
    const id = Number(props.id);

    if (!id) {
        return <div>Loading</div>;
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="project_details">
                <Header />
                
                <div className="top">
                    <h1>{EachProjectData[id-1].title}</h1>
                    <div className="subtitle">{EachProjectData[id-1].subtitle}</div>
                    <video width="1000px" poster={EachProjectData[id-1].poster} controls>
                        <source src={EachProjectData[id-1].video} type="video/mp4" />
                    </video>
                </div>

                <section className="about">
                    <div className="title">About the project.</div>
                    <div className="text">
                        {EachProjectData[id-1].about.map((p) => (
                            <p>{p}</p>
                        ))}
                    </div>
                </section>

                <section className="stacks">
                    <div className="title">Stacks I used<span>.</span></div>
                    <div className="texts">
                        {EachProjectData[id-1].stacks.map((s) => (
                            <div>{s}</div>
                        ))}
                    </div>
                </section>
            </main>
        </>
    )
}

export default ProjectDetail